version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=student_management_system.settings
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/student_management
    depends_on:
      - db
    networks:
      - student_network
    command: >
      bash -c "
        while ! nc -z db 5432; do
          echo 'Waiting for database to be ready...'
          sleep 1
        done;
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=student_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - student_network

networks:
  student_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
